[tool.poetry]
name = "sillycation"
packages = [
    { include = "sillycation" },
]
version = "2.4.1"
description = "A web application for groups of friends to collect, vote on, and rank memorable moments from their trips."
authors = ["Arianna Cortesi <arianna.cortesi2@unibo.it>", 
            "Camilla Iocca <camilla.iocca@studio.unibo.it>",
            "Chiara Avoni <chiara.avoni@studio.unibo.it>"]
license = "Apache 2.0"
readme = "README.md"

[tool.poetry.dependencies]
# update the Python versions in .github/workflows/check.yml if you change this
python = ">= 3.9.0 < 4.0.0"

[tool.poetry.group.dev.dependencies]
coverage = "^7.4.0"
mypy = "^1.10.1"
poethepoet = "^0.37.0"
poetry = "^1.8.3"
pytest = "^8.3.5"
ruff = "^0.15.0"

[tool.poe.tasks]
test = "pytest"
coverage = "coverage run -m pytest"
coverage-report = "coverage report -m"
coverage-html = "coverage html"
ruff-check = "ruff check"
ruff-fix = "ruff check --fix"
format = "ruff format"
format-check = "ruff format --check"
mypy = "mypy sillycation tests"
compile = "python -m compileall Artifact tests"
static-checks = [
    "ruff-check",
    "mypy",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
